linux-hp-tenderloin: include ".rootfs" with ${IMAGE_NAME_SUFFIX} in IMAGE_BOOT_FILES initramfs-uboot-image
* With my do_deploy changes in oe-core/jansa/master the suffix is back.

* fixes:
  ERROR: linux-hp-tenderloin-5.19-rc7+gitrAUTOINC+f55df88ad1_6d76455e1d-r0
  do_deploy: Required initramfs uImage
  /OE/build/luneos-langdale/webos-ports/tmp-glibc/deploy/images/tenderloin/initramfs-uboot-image-tenderloin.cpio.gz.u-boot
  is not available!

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>